#!/usr/bin/env python
import os
import sys

#os.system('cd docs/; make html; cd ../;')
return_val = os.system('pytest --cov=rcwa/source --cov-report html')
exit_status = os.WEXITSTATUS(return_val)
print(f'exit status: {exit_status}')
if exit_status == 0:
    os.system('coverage html')
    sys.exit(0)
else:
    sys.exit(exit_status)
